### ISSUE TITLE
Pedido de remoção

### ISSUE THREAD

**Issue by takedownsantana** [Netaum/ci-jenkins#4]
Prezado Usuário,

A Apura Cyber Security foi contratada pela RAÍZEN para remover conteúdo que contenha propriedade intelectual da empresa ou tenha como alvo sua infraestrutura.

Deste modo, solicito, cordiamente, que remova este repositório.

Certo de que seremos atendidos, me despeço com votos de elevada estima.

Julius Santana
Advogado
Apura Cybersecurity.

**Comment by Netaum** [comment]
Todos os dados pertencentes a raizen foram removidos do repo.
